DATABASE_URL: "postgresql://postgres:Muneca1213%23%23@db.dppqzgdbkzsvrpqvvorh.supabase.co:5432/postgres"
SECRET_KEY: "prod-secret-key-matrixcalc-2025"
DEBUG: "True"
ALLOWED_HOSTS: "*"
CORS_ALLOW_ALL_ORIGINS: "True"
CORS_ALLOW_CREDENTIALS: "True"
CORS_ALLOW_HEADERS: "accept, accept-encoding, authorization, content-type, dnt, origin, user-agent, x-csrftoken, x-requested-with"
CORS_ALLOW_METHODS: "DELETE, GET, OPTIONS, PATCH, POST, PUT"
